/* Generated by re2c 0.16 on Wed Apr 24 15:07:41 2019 */
#line 1 "process.re"
/*----------------------------------------------------------------------
  process.re - re2c source to generate command line tokenizer
 */
 
#include <stdio.h>
#include <stdlib.h>
#include "process.h"

#define YYMAXFILL 5

bool process(process_t *scanner)
{
    const char *YYMARKER=0;
    const char *s = scanner->stok;
loop:
    
#line 20 "process.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *s;
	switch (yych) {
	case 0x00:
	case '\r':	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	case '?':	goto yy12;
	case 'B':
	case 'b':	goto yy14;
	case 'H':
	case 'h':	goto yy15;
	case 'L':
	case 'l':	goto yy16;
	case 'O':
	case 'o':	goto yy17;
	default:	goto yy4;
	}
yy2:
	++s;
#line 26 "process.re"
	{ scanner->tok=END;     goto process_exit; }
#line 54 "process.cpp"
yy4:
	++s;
yy5:
#line 27 "process.re"
	{ scanner->tok=yych;    goto process_exit; }
#line 60 "process.cpp"
yy6:
	++s;
	yych = *s;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 28 "process.re"
	{ scanner->stok=s;      goto loop;         }
#line 72 "process.cpp"
yy9:
	++s;
	yych = *s;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	default:	goto yy11;
	}
yy11:
#line 29 "process.re"
	{ scanner->tok=DEC;     goto process_exit; }
#line 92 "process.cpp"
yy12:
	++s;
yy13:
#line 30 "process.re"
	{ scanner->tok=HELP;    goto process_exit; }
#line 98 "process.cpp"
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'L':
	case 'l':	goto yy18;
	default:	goto yy5;
	}
yy15:
	yyaccept = 1;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'E':
	case 'e':	goto yy20;
	default:	goto yy13;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'E':
	case 'e':	goto yy21;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++s);
	switch (yych) {
	case 'F':
	case 'f':	goto yy22;
	case 'N':
	case 'n':	goto yy23;
	default:	goto yy5;
	}
yy18:
	yych = *++s;
	switch (yych) {
	case 'I':
	case 'i':	goto yy25;
	default:	goto yy19;
	}
yy19:
	s = YYMARKER;
	if (yyaccept == 0) {
		goto yy5;
	} else {
		goto yy13;
	}
yy20:
	yych = *++s;
	switch (yych) {
	case 'L':
	case 'l':	goto yy26;
	default:	goto yy19;
	}
yy21:
	yych = *++s;
	switch (yych) {
	case 'D':
	case 'd':	goto yy27;
	default:	goto yy19;
	}
yy22:
	yych = *++s;
	switch (yych) {
	case 'F':
	case 'f':	goto yy29;
	default:	goto yy19;
	}
yy23:
	++s;
#line 34 "process.re"
	{ scanner->tok=ON;      goto process_exit; }
#line 172 "process.cpp"
yy25:
	yych = *++s;
	switch (yych) {
	case 'N':
	case 'n':	goto yy31;
	default:	goto yy19;
	}
yy26:
	yych = *++s;
	switch (yych) {
	case 'P':
	case 'p':	goto yy12;
	default:	goto yy19;
	}
yy27:
	++s;
#line 31 "process.re"
	{ scanner->tok=LED;     goto process_exit; }
#line 191 "process.cpp"
yy29:
	++s;
#line 33 "process.re"
	{ scanner->tok=OFF;     goto process_exit; }
#line 196 "process.cpp"
yy31:
	yych = *++s;
	switch (yych) {
	case 'K':
	case 'k':	goto yy32;
	default:	goto yy19;
	}
yy32:
	++s;
#line 32 "process.re"
	{ scanner->tok=BLINK;   goto process_exit; }
#line 208 "process.cpp"
}
#line 35 "process.re"


process_exit:
    scanner->cursor = s; // set up YYCURSOR scan
    scanner->len = (scanner->cursor - scanner->stok);

    if ( scanner->tok == DEC) {
        scanner->value = strtol(scanner->stok,0,10);
    }
    else {
        scanner->value = 0;
    }
        
    return ( scanner->tok == END ) ? true : false;
}
